version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    ECR_REPO_NAME: "user37-front-ecr"
    AWS_ACCOUNT_ID: "416225317325"
    EKS_CLUSTER_NAME: "user37-eks-cluster"

phases:
  install:
    commands:
      - echo "=> kubectl 설치 중..."
      - curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.29.0/2024-01-04/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
  pre_build:
    commands:
      - echo "=> Amazon ECR에 로그인합니다..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo "=> Nginx 기반 프론트엔드 Docker 이미지를 빌드합니다..."
      - docker build -t $ECR_REPO_NAME:latest .
      - docker tag $ECR_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:latest
  post_build:
    commands:
      - echo "=> 빌드된 이미지를 ECR로 푸시합니다..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:latest
      - echo "=> EKS 클러스터 인증 정보를 업데이트합니다..."
      - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $EKS_CLUSTER_NAME
      - echo "=> EKS에 프론트엔드 리소스를 배포합니다..."
      - kubectl apply -f kubernetes/deployment.yaml
      - kubectl apply -f kubernetes/service.yaml
      - kubectl rollout restart deployment/front-deployment
      - echo "=> EKS 프론트엔드 배포 완료!"
