server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # /api/로 들어오는 요청을 EKS 내부의 백엔드 서비스로 전달
    location /api/ {
        proxy_pass http://user37-back-service.default.svc.cluster.local:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}